config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  get 'users/new', to: 'users#new', as: :create_student
  post 'users', to: 'users#create'
  resources :books do
    resources :reservations, only: [ :new, :create, :update ]
  end
  resources :reservations, only: [ :index ]
  get 'reservations/my_reservations', to: 'reservations#my_reservations', as: :my_reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reservations
  validates :stock, numericality: {greater_than_or_equal_to: 0}
  validates :published_year, numericality: {greater_than_or_equal_to: 868}
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR author ILIKE :query OR genre ILIKE :query"
      @books = Book.where(sql_query, query: "%#{params[:query]}%")
    else
      @books = Book.all
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @book.update(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :published_year, :genre, :stock)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    phrases = ['“The books that the world calls immoral are books that show the world its own shame.” ―Oscar Wilde',
      '“Books are a uniquely portable magic.” ―Stephen King', '
      “... a mind needs books as a sword needs a whetstone, if it is to keep its edge.”
      ―George R.R. Marti', '“Only the very weak-minded refuse to be influenced by literature and poetry.”
      ―Cassandra Clare', '
      “A great book should leave you with many experiences, and slightly exhausted at the end. You live several lives while reading.”
      ―William Styron']

    @line = phrases[rand(0..4)]
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :set_reservation, only: [:update]

  def index
    if params[:query].present?
      sql_query = <<~SQL
        users.first_name ILIKE :query
        OR users.last_name ILIKE :query
        OR users.email ILIKE :query
        SQL
      @reservations = Reservation.joins(:user).where(sql_query, query: "%#{params[:query]}%").and(Reservation.all.where(reserved: true))
    else
      @reservations = Reservation.all.where(reserved: true)
    end
  end

  def my_reservations
    @open_reservations = Reservation.all.where(reserved: true).and(Reservation.all.where(user: current_user))
    @closed_reservations = Reservation.all.where(reserved: false).and(Reservation.all.where(user: current_user))
  end

  def new
    @book = Book.find(params[:book_id])
    @user = current_user
    @reservation = Reservation.new
  end

  def create
    @book = Book.find(params[:book_id])
    @user = current_user
    @reservation = Reservation.new
    @reservation.book = @book
    @reservation.user = @user
    @reservation.reserved = true
    if @reservation.save
      @book.stock -= 1
      @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @reservation.reserved = false
    @reservation.book.stock += 1
    @reservation.book.save
    if @reservation.save
      redirect_to reservations_path
    else
      render :new
    end

  end

  def show
  end

  def destroy
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="container-add-book">
  <%= simple_form_for( @book ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }%>
      <%= f.input :author,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :published_year,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :genre,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :stock,
                  required: true,
                  hint: ("1 minimum"),
                  input_html: { autocomplete: "new-password" } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Edit Book", class: "btn btn-ghost", id:"log-out"%>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<div class= "search">
  <%= form_tag books_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a book"
    %>
    <%= submit_tag "Search", class: "btn btn-ghost", id:"log-out" %>
  <% end %>
</div>
<div class="container-book-index">
  <% if @books.empty? %>
      <h3 class="search-result">Book not found</h3>
  <% else %>
    <% @books.each do |book| %>
      <div class="book-info">
        <p><strong><%= book.title %></strong></p>
        <p><%= book.author %></p>
        <%= link_to "view", book_path(book), class: "btn btn-ghost", id:"book-view"%>
      </div>
    <% end %>
  <% end %>

</div>

app/views/books/new.html.erb
<div class="container-add-book">
  <%= simple_form_for( @book ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }%>
      <%= f.input :author,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :published_year,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :genre,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :stock,
                  required: true,
                  hint: ("1 minimum"),
                  input_html: { autocomplete: "new-password" } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Add Book", class: "btn btn-ghost", id:"log-out"%>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container-show-book">
    <div class="show-img">
      <%= image_tag "Book.png", class: "img-book-show" %>
    </div>
    <div class="book-data">
      <h4 class= title-book><strong><%=@book.title%></strong></h4>
      <p><strong>Author: </strong><%=@book.author%></p>
      <p><strong>Published: </strong><%=@book.published_year%></p>
      <p><strong>Genre: </strong><%=@book.genre%></p>
    <% if @book.stock == 0 %>
      <p><strong>This book is out of stock</strong></p>
    <% else %>
      <% if user_signed_in? %>
        <p><strong>stock: </strong><%=@book.stock%></p>
        <% user = current_user %>
        <% if user.role %>
          <%= link_to "Edit book", edit_book_path(@book),class: "btn btn-ghost", id:"reserve-book"%>
        <% else %>
          <%= link_to "Reserve book", book_reservations_path(@book),class: "btn btn-ghost", id:"reserve-book", method: :post %>
        <% end %>
      <% else %>
        <p><strong>stock: </strong><%=@book.stock%></p>
        <%= link_to "Reserve book", new_user_session_path,class: "btn btn-ghost", id:"reserve-book", method: :post %>
      <% end %>
    <% end %>
    </div>
</div>
<div class="container">
<%= link_to "Back", books_path, class: "btn btn-ghost", id:"log-out" %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalLibrary</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><%= render "shared/navbar"%>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="phrase">
    <p><%= @line %></p>
  </div>
  <div class="home-btn">
    <%= link_to 'Start Reading', books_path, class: "btn btn-ghost", id:"log-in" %>
  </div>
</div>
<div class="footer">
  <div class="steps">
    <div class="step">
      <h4>Find your book</h4>
      <i class="fas fa-search"></i>
    </div>
    <div class="step">
      <h4>Reserve it</h4>
      <i class="far fa-bookmark"></i>
    </div>
    <div class="step">
      <h4>Read it!</h4>
      <i class="fa fa-book"></i>
    </div>
    <div class="step">
      <h4>Return it</h4>
      <i class="far fa-check-circle"></i>
    </div>
  </div>
</div>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<div class= "search">
  <%= form_tag reservations_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a student"
  %>
  <%= submit_tag "Search", class: "btn btn-ghost", id:"log-out" %>
<% end %>
</div>
<div class="container-book-index">
  <% if @reservations.empty? %>
      <h3 class= "search-result">Student not found</h3>
  <% else %>
    <% @reservations.each do |reservation| %>
      <div class="book-info">
        <p><strong>Book:</strong> <%= reservation.book.title %></p>
        <p><strong>Student:</strong> <%= reservation.user.first_name %></p>
        <%= link_to "Mark as returned", book_reservation_path(reservation.book.id, reservation.id), class: "btn btn-ghost", id:"book-view-2", method: :patch %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reservations/my_reservations.html.erb
<div class="container">
  <h2 class= "headline">Active Reservations</h2>
  <div class="container-book-index">
    <% @open_reservations.each do |reservation| %>
      <div class="book-info">
        <p><%= reservation.book.title %></p>
        <%= image_tag "open-book.png", class: "img-book" %>
      </div>
    <% end %>
  </div>
  <h2 class= "headline">Previous Reservations</h2>
  <div class="container-book-index">
    <% @closed_reservations.each do |reservation| %>
      <div class="book-info">
        <p><%= reservation.book.title %></p>
        <%= image_tag "closed-book.png", class: "img-book-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="p-3  header nav-bar sticky-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
    <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
              <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <%= image_tag "Logo.png", class: "logo" %>
              </a>

              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <% if current_user.role %>
                  <li class="nav-li"><%= link_to 'Home', root_path, class: "nav-link px-2" %></li>
                  <li class="nav-li"><%= link_to 'Books', books_path, class: "nav-link px-2" %></li>
                  <li class="nav-li"><%= link_to 'Add Book', new_book_path, class: "nav-link px-2" %></li>
                  <li class="nav-li"><%= link_to 'Active Reservations', reservations_path, class: "nav-link px-2" %></li>
                  <li class="nav-li"><%= link_to 'Create Student Profile', create_student_path, class: "nav-link px-2" %></li>
                <% else %>
                  <li class="nav-li"><%= link_to 'Home', root_path, class: "nav-link px-2" %></li>
                  <li class="nav-li"><%= link_to 'Books', books_path, class: "nav-link px-2" %></li>
                  <li class="nav-li"><%= link_to 'My Reservations', my_reservations_path, class: "nav-link px-2" %></li>
                <% end %>
              </ul>

              <div class="dropdown text-end">
                <div>
                  <span class= "username"><%= current_user.first_name.capitalize %></span>
                  <%= link_to 'Log out', destroy_user_session_path, method: 'delete', class: "btn btn-ghost", id:"log-out" %>
                </div>
              </div>
            </div>
          </div>
  </div>
<% else %>
  <div class="p-3  header nav-bar sticky-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
    <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
              <%= image_tag "Logo.png", class: "logo" %>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li class="nav-li"><%= link_to 'Home', root_path, class: "nav-link px-2" %></li>
              <li class="nav-li"><%= link_to 'Books', books_path, class: "nav-link px-2" %></li>
                <li class="nav-li"><%= link_to 'My Reservations', new_user_session_path, class: "nav-link px-2" %></li>
            </ul>

            <div>
              <%= link_to 'Log in', new_user_session_path, class: "btn btn-ghost", id:"log-in" %>
            </div>
          </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container-login">
  <%= simple_form_for( @user ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }%>
      <%= f.input :last_name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :email,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "email" }%>
      <%= f.input :role,
                  label: 'Librarian',
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "last name" }%>
      <%= f.input :password,
                  required: true,
                  hint: ("6 characters minimum" if 6),
                  input_html: { autocomplete: "new-password" } %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Create", class: "btn btn-ghost", id:"log-out" %>
    </div>
  <% end %>
</div>